### ISSUE TITLE
CalibrationTxMessage, SessionStartTxMessage, SessionStopTxMessage

### ISSUE THREAD

**Issue by mthatcher** [loudnate/xDripG5#34]
Hey, first off, **thank you** so incredibly much for all of the awesome work you've put into this project. It's been instrumental in getting my readings onto my android device. I'm pretty close to being ready to open the project up, but in the mean time I thought I'd share some of the messages I've been able to decipher. Unfortunately I don't code swift well enough to give you a pull request, but hopefully I've documented the messages well enough that you can easily whip them out in swift. Attached [here](https://github.com/loudnate/xDripG5/files/297964/TxMessages.zip) are the java files for CalibrationTxMessage, SessionStartTxMessage, and SessionStopTxMessage.

**Comment by loudnate** [comment]
This is great, thanks!

**Comment by loudnate** [comment]
So I'm surprised to see that your `SessionStartTxMessage` captures look different than mine; mine don't contain the `uint32_t` UTC clock value (they look just like the `SessionStopTxMessage`). Mine were from last fall, though; maybe this changed with a receiver firmware or iOS app update?

**Comment by mthatcher** [comment]
Interesting... The sample captures I included at the bottom of those files were from the IOS Dexcom app version 1.2.1. With the following transmitter stats:
AB 11106161
Firmware 1.0.0.17
Software Number SW10719

I got my display (i.e. not the ios app) in October or so, I don't have it with me so I can't check what version it's running but its packets look the same. The display's session start packet is the packet in the table at the top of the class.

```
+--------+---------------------------------+------------------------------+--------+
| [0]    | [1-4]                           | [5-8]                        | [9-10] |
+--------+---------------------------------+------------------------------+--------+
| opcode | sessionStartTimeInDexcomSeconds | sessionStartTimeInUTCSeconds | CRC    |
+--------+---------------------------------+------------------------------+--------+
| 26     | d6 02 00 00                     | e8 2f 75 0d                  | 66 a6  |
+--------+---------------------------------+------------------------------+--------+

```
It's interesting to note that the second time value is e8 2f 75 0d or in decimal 225783784 which ends up being Fri Feb 25 1977 22:43:04 in UTC seconds. So I'm betting that value should probably be treated as more of a "clientClock" value rather having to be UTC. Also I assume it's just acting as more of an FYI to the transmitter rather than anything it's actually using.

**Comment by scottc5** [comment]
Just a thought but maybe the time is an endianess issue?
-Myles

On Mon, Jun 06, 2016 at 11:27 AM, Mike Thatcher <notifications@github.com<mailto:notifications@github.com>> wrote:


Interesting... The sample captures I included at the bottom of those files were from the IOS Dexcom app version 1.2.1. With the following transmitter stats:
AB 11106161
Firmware 1.0.0.17
Software Number SW10719

I got my display (i.e. not the ios app) in October or so, I don't have it with me so I can't check what version it's running but its packets look the same. The display's session start packet is the packet in the table at the top of the class.

+--------+---------------------------------+------------------------------+--------+
| [0]    | [1-4]                           | [5-8]                        | [9-10] |
+--------+---------------------------------+------------------------------+--------+
| opcode | sessionStartTimeInDexcomSeconds | sessionStartTimeInUTCSeconds | CRC    |
+--------+---------------------------------+------------------------------+--------+
| 26     | d6 02 00 00                     | e8 2f 75 0d                  | 66 a6  |
+--------+---------------------------------+------------------------------+--------+



It's interesting to note that the second time value is e8 2f 75 0d or in decimal 225783784 which ends up being Fri Feb 25 1977 22:43:04 in UTC seconds. So I'm betting that value should probably be treated as more of a "clientClock" value rather having to be UTC. Also I assume it's just acting as more of an FYI to the transmitter rather than anything it's actually using.

-

**Comment by loudnate** [comment]
`NSDate` uses an epoch internally of Jan 1 2001, could it be that?

**Comment by loudnate** [comment]
I don't see any evidence anywhere else of the transmitter caring about any clock except its internal one.

**Comment by loudnate** [comment]
New messages added and released, thanks!
